#!/usr/bin/env bash
#istrozitation

sudo apt install -y nginx
sh -c 'echo "Hello World!" >/var/www/html/index.html'
sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
}" >> /etc/nginx/sites-available/default'
sudo service nginx restart
