#!/usr/bin/env bash
#istrozitation

sudo apt install -y nginx
echo "Hello World!" >/var/www/html/index.html
echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
}" >> /etc/nginx/sites-available/default
sudo service nginx restart
