#!/usr/bin/env bash
#azeoaepaedoak
sudo apt -y update
sudo apt -y install nginx
sh -c 'echo "Hello World!" | tee /var/www/html/index.html'
sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
    }
    
    location /redirect_me {
        return 301 http://54.144.144.29
    }
}" >> /etc/nginx/sites-available/default'
sudo service nginx restart
