#!/usr/bin/env bash
#ezaeazeazeazea
sudo service nginx start
sudo rm -f /etc/nginx/sites-available/default

sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
        add_header X-Served-By $(hostname);
        autoindex on;
    }
}" | sudo tee /etc/nginx/sites-available/default'

sudo service nginx restart
