#!/usr/bin/env bash
#ezaeazeazeazea
sudo apt-get -y update
sudo apt-get -y install nginx
sh -c 'echo "server {
    listen 80;
    server_name localhost;

    location / {
        root /var/www/html;
        index index.html;
        add_header X-Served-By $(hostname);
        autoindex on;
    }
}" >> /etc/nginx/sites-available/default'

sudo service nginx restart

