#!/usr/bin/env bash
# Configure your Nginx server to have a custom 404 page that contains the string Ceci n'est pas une page.
host=$(hostname)
apt-get -y update
apt-get -y install nginx
echo "server {
    listen 80 default_server;

    location / {
        add_header X-Served-By $host;
    }
}" >/etc/nginx/sites-available/default
sudo service nginx restart
