#!/usr/bin/env bash
#ezaazeoo
sudo apt-get -y update
sudo apt-get install -y haproxy
sh -c 'echo "
frontend front
    bind *:80
    default_backend back

backend back
    balance roundrobin
    server web1 54.144.144.29:80 check
    server web2 54.158.205.242:80 check
    " >> /etc/haproxy/haproxy.cfg'

sudo service haproxy restart
