#!/usr/bin/env bash
#100

sudo touch /var/run/myscript.pid

while true; do
    echo To infinity and beyond

    trap 'echo I hate the kill command; sudo rm -rf /var/run/myscript.pid; exit' SIGTERM
    trap 'echo Y U no love me?!' SIGINT
    trap 'sudo rm -rf /var/run/myscript.pid; exit' SIGQUIT

    sleep 2
done;