#!/usr/bin/env bash
#OKOK

process_name="bash"
pid=$(pgrep -o "$process_name")

if [ -n "$pid" ]; then
    kill "$pid"
    echo "Terminated process '$process_name' with PID $pid."
else
    echo "Process '$process_name' not found or not running."
fi
