#!/usr/bin/env bash
#fileMan

if [ -e "school" ]; then
    echo school file exist

    if [ -s "school" ]; then
        echo school file is empty
    else
        echo school file is not empty
    fi

    if [ -f "school" ]; then
        echo school file is regular
    fi
else
    echo school file does not exist
fi
