#!/usr/bin/env bash
#USERCHANGEYOURHOMEIPPLEASEHIHACHIM
echo "8.8.8.8 facebook.com" | sudo tee -a /etc/hosts
sudo cp /etc/hosts ~/hosts.new
sed -i s/127.0.0.1/127.0.0.2/ ~/hosts.new
sudo cp -f ~/hosts.new /etc/hosts

